#!/bin/bash
vchange=`git pull`
#version=`git reset --hard origin/master`

	if  [ "$vchange" == 'Already up-to-date.' ] ; then 
                echo ==============================      
                echo Gridcoin Wallet is up-do-date!
                echo ==============================
               
exit
        fi
                echo `date` >> grcs_vlogs.txt
                echo $vchange >> grcs_vlogs.txt #Copies the git change information into the log file
		echo ==========================     
		echo Stating update sequence...
                echo ========================== 
                read -p "Push enter to close the running Gridcoin wallet."
                killall gridcoinresearch
                echo "Gridcoin wallet has been closed"
                echo  "Did you install Boost 1.55 by hand in the root directory (j/n)?:"
                read  boost
                        if [  $boost == "j" ]; then
                               sed -i -e '35iBOOST_INCLUDE_PATH = /boost/boost_1_55_0/' \
                                       -e '36iBOOST_LIB_PATH = /boost/boost_1_55_0/stage/lib/' \
                                          gridcoinstake.pro

                        fi
                                sed -i 's/QT += qaxcontainer/CONFIG += qaxcontainer/' gridcoinstake.pro
                                chmod 755 src/leveldb/build_detect_platform
                                mkdir src/obj/zerocoin
                        if [[ -e $(which qmake-qt4) ]]; then
                                qmake-qt4 'USE_UPNP=-'
                                else
                                qmake 'USE_UPNP=-'
                        fi
                                make
                                strip gridcoinresearch
                                chmod 755 gridcoinresearch
				echo ================================================================================
                                echo "Update done! Please start the Gridcoin wallet to check." 
                                echo ================================================================================
                        exit

exit 0